#aliases:
#  - &armcc
#    match-compiler-exe: "(.*/)?armcc(\\.exe)?"
#    code-insight-target-name: arm
#    include-dirs: ${compiler-exe-dir}/../include
#    defines:
#      __disable_irq(): # define builtin as empty
#      __enable_irq(): # define builtin as empty

compilers:
  - description: Tricore C Compiler
    match-compiler-exe: "(.*/)?tricore-(elf-)?gcc(\\.exe)?"
    match-language: C
    match-sources: ".*\\.c"
    include-dirs: ${compiler-exe-dir}/../tricore/include
    defines-text: "
#define __DBL_MIN_EXP__ (-1021)
#define __UINT_LEAST16_MAX__ 65535
#define __ATOMIC_ACQUIRE 2
#define __FLT_MIN__ 1.1754943508222875e-38F
#define __GCC_IEC_559_COMPLEX 0
#define __UINT_LEAST8_TYPE__ unsigned char
#define __INTMAX_C(c) c ## LL
#define __CHAR_BIT__ 8
#define __UINT8_MAX__ 255
#define __WINT_MAX__ 4294967295U
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __SIZE_MAX__ 4294967295UL
#define __WCHAR_MAX__ 2147483647
#define __DBL_DENORM_MIN__ ((double)4.9406564584124654e-324L)
#define __GCC_ATOMIC_CHAR_LOCK_FREE 1
#define __GCC_IEC_559 0
#define __FLT_EVAL_METHOD__ 0
#define __GCC_ATOMIC_CHAR32_T_LOCK_FREE 1
#define __UINT_FAST64_MAX__ 18446744073709551615ULL
#define __SIG_ATOMIC_TYPE__ int
#define __DBL_MIN_10_EXP__ (-307)
#define __FINITE_MATH_ONLY__ 0
#define __GNUC_PATCHLEVEL__ 4
#define __UINT_FAST8_MAX__ 4294967295U
#define __has_include(STR) __has_include__(STR)
#define __DEC64_MAX_EXP__ 385
#define __INT8_C(c) c
#define __UINT_LEAST64_MAX__ 18446744073709551615ULL
#define __SHRT_MAX__ 32767
#define __LDBL_MAX__ 1.7976931348623157e+308L
#define __UINT_LEAST8_MAX__ 255
#define __GCC_ATOMIC_BOOL_LOCK_FREE 1
#define __UINTMAX_TYPE__ long long unsigned int
#define __BUILTIN_TRICORE_INSERT 1
#define __DEC32_EPSILON__ 1E-6DF
#define __UINT32_MAX__ 4294967295UL
#define __TRICORE_HAVE_SHUFFLE__ 1
#define __LDBL_MAX_EXP__ 1024
#define __WINT_MIN__ 0U
#define __SCHAR_MAX__ 127
#define __WCHAR_MIN__ (-__WCHAR_MAX__ - 1)
#define __INT64_C(c) c ## LL
#define __DBL_DIG__ 15
#define __TRICORE_CORE__ 0x162
#define __GCC_ATOMIC_POINTER_LOCK_FREE 1
#define __TRICORE_HAVE_MOV64__ 1
#define __SIZEOF_INT__ 4
#define __SIZEOF_POINTER__ 4
#define __USER_LABEL_PREFIX__
#define __STDC_HOSTED__ 1
#define __LDBL_HAS_INFINITY__ 1
#define __TRICORE_HAVE_DIV__ 1
#define __FLT_EPSILON__ 1.1920928955078125e-7F
#define __BUILTIN_TRICORE_SATB 1
#define __LDBL_MIN__ 2.2250738585072014e-308L
#define __BUILTIN_TRICORE_SATH 1
#define __DEC32_MAX__ 9.999999E96DF
#define __INT32_MAX__ 2147483647L
#define __SIZEOF_LONG__ 4
#define __STDC_ISO_10646__ 200009L
#define __UINT16_C(c) c
#define __DECIMAL_DIG__ 17
#define __has_include_next(STR) __has_include_next__(STR)
#define __LDBL_HAS_QUIET_NAN__ 1
#define __GNUC__ 4
#define __FLT_HAS_DENORM__ 1
#define __SIZEOF_LONG_DOUBLE__ 8
#define __BIGGEST_ALIGNMENT__ 4
#define __DBL_MAX__ ((double)1.7976931348623157e+308L)
#define __INT_FAST32_MAX__ 2147483647
#define __DBL_HAS_INFINITY__ 1
#define __DEC32_MIN_EXP__ (-94)
#define __INT_FAST16_TYPE__ int
#define __STRICT_ANSI__ 1
#define __LDBL_HAS_DENORM__ 1
#define __DEC128_MAX__ 9.999999999999999999999999999999999E6144DL
#define __INT_LEAST32_MAX__ 2147483647L
#define __USING_SJLJ_EXCEPTIONS__ 1
#define __DEC32_MIN__ 1E-95DF
#define __DBL_MAX_EXP__ 1024
#define __DEC128_EPSILON__ 1E-33DL
#define __PTRDIFF_MAX__ 2147483647L
#define __STDC_NO_THREADS__ 1
#define __LONG_LONG_MAX__ 9223372036854775807LL
#define __SIZEOF_SIZE_T__ 4
#define __SIZEOF_WINT_T__ 4
#define __STDC_NO_ATOMICS__ 1
#define __GXX_ABI_VERSION 1002
#define __BUILTIN_TRICORE_CMPSWAPW 1
#define __FLT_MIN_EXP__ (-125)
#define __BUILTIN_TRICORE_LROTATE 1
#define __tricore__ 1
#define __INT_FAST64_TYPE__ long long int
#define __FP_FAST_FMAF 1
#define __DBL_MIN__ ((double)2.2250738585072014e-308L)
#define __DEC128_MIN__ 1E-6143DL
#define __REGISTER_PREFIX__ %
#define __UINT16_MAX__ 65535
#define __DBL_HAS_DENORM__ 1
#define __UINT8_TYPE__ unsigned char
#define __NO_INLINE__ 1
#define __BUILTIN_TRICORE_SWAPMSKW 1
#define __FLT_MANT_DIG__ 24
#define __VERSION__ \"4.9.4 build on 2020-09-01\"
#define __UINT64_C(c) c ## ULL
#define __HIGHTEC__ 1
#define __tricore 1
#define _STDC_PREDEF_H 1
#define __TC162__ 1
#define __GCC_ATOMIC_INT_LOCK_FREE 1
#define __TRICORE_HAVE_LHA__ 1
#define __FLOAT_WORD_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __BUILTIN_TRICORE_RROTATE 1
#define __TRICORE_HAVE_FLOAT16__ 1
#define __INT32_C(c) c ## L
#define __DEC64_EPSILON__ 1E-15DD
#define __ORDER_PDP_ENDIAN__ 3412
#define __DEC128_MIN_EXP__ (-6142)
#define __INT_FAST32_TYPE__ int
#define __UINT_LEAST16_TYPE__ short unsigned int
#define __INT16_MAX__ 32767
#define __SIZE_TYPE__ long unsigned int
#define __UINT64_MAX__ 18446744073709551615ULL
#define __INT8_TYPE__ signed char
#define __ELF__ 1
#define __FLT_RADIX__ 2
#define __INT_LEAST16_TYPE__ short int
#define __LDBL_EPSILON__ 2.2204460492503131e-16L
#define __UINTMAX_C(c) c ## ULL
#define __SIG_ATOMIC_MAX__ 2147483647
#define __GCC_ATOMIC_WCHAR_T_LOCK_FREE 1
#define __SIZEOF_PTRDIFF_T__ 4
#define __BUILTIN_TRICORE_SWAPW 1
#define __DEC32_SUBNORMAL_MIN__ 0.000001E-95DF
#define __INT_FAST16_MAX__ 2147483647
#define __UINT_FAST32_MAX__ 4294967295U
#define __UINT_LEAST64_TYPE__ long long unsigned int
#define __FLT_HAS_QUIET_NAN__ 1
#define __FLT_MAX_10_EXP__ 38
#define __LONG_MAX__ 2147483647L
#define __TRICORE_HAVE_HPTOF__ 1
#define __DEC128_SUBNORMAL_MIN__ 0.000000000000000000000000000000001E-6143DL
#define __FLT_HAS_INFINITY__ 1
#define __BUILTIN_TRICORE_LDMST 1
#define __UINT_FAST16_TYPE__ unsigned int
#define __DEC64_MAX__ 9.999999999999999E384DD
#define __CHAR16_TYPE__ short unsigned int
#define __PRAGMA_REDEFINE_EXTNAME 1
#define __TRICORE_HAVE_FTOHP__ 1
#define __INT_LEAST16_MAX__ 32767
#define __DEC64_MANT_DIG__ 16
#define __INT64_MAX__ 9223372036854775807LL
#define __UINT_LEAST32_MAX__ 4294967295UL
#define __GCC_ATOMIC_LONG_LOCK_FREE 1
#define __INT_LEAST64_TYPE__ long long int
#define __INT16_TYPE__ short int
#define __INT_LEAST8_TYPE__ signed char
#define __STDC_VERSION__ 199901L
#define __DEC32_MAX_EXP__ 97
#define __INT_FAST8_MAX__ 2147483647
#define __INTPTR_MAX__ 2147483647L
#define __LDBL_MANT_DIG__ 53
#define __DBL_HAS_QUIET_NAN__ 1
#define __SIG_ATOMIC_MIN__ (-__SIG_ATOMIC_MAX__ - 1)
#define __INTPTR_TYPE__ long int
#define __UINT16_TYPE__ short unsigned int
#define __WCHAR_TYPE__ int
#define __SIZEOF_FLOAT__ 4
#define __UINTPTR_MAX__ 4294967295UL
#define __DEC64_MIN_EXP__ (-382)
#define __INT_FAST64_MAX__ 9223372036854775807LL
#define __GCC_ATOMIC_TEST_AND_SET_TRUEVAL 1
#define __FLT_DIG__ 6
#define __UINT_FAST64_TYPE__ long long unsigned int
#define __TRICORE_HAVE_CRCN__ 1
#define __INT_MAX__ 2147483647
#define __TRICORE_HAVE_FTOIZ__ 1
#define __INT64_TYPE__ long long int
#define __FLT_MAX_EXP__ 128
#define __DBL_MANT_DIG__ 53
#define __INT_LEAST64_MAX__ 9223372036854775807LL
#define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 1
#define __DEC64_MIN__ 1E-383DD
#define __WINT_TYPE__ unsigned int
#define __UINT_LEAST32_TYPE__ long unsigned int
#define __SIZEOF_SHORT__ 2
#define __LDBL_MIN_EXP__ (-1021)
#define __INT_LEAST8_MAX__ 127
#define __TRICORE_HAVE_POPCNT__ 1
#define __LDBL_MAX_10_EXP__ 308
#define __ATOMIC_RELAXED 0
#define __DBL_EPSILON__ ((double)2.2204460492503131e-16L)
#define __BUILTIN_TRICORE_IMASK 1
#define __UINT8_C(c) c
#define __INT_LEAST32_TYPE__ long int
#define __SIZEOF_WCHAR_T__ 4
#define __UINT64_TYPE__ long long unsigned int
#define __TRICORE__ 1
#define __INT_FAST8_TYPE__ int
#define __GNUC_STDC_INLINE__ 1
#define __DBL_DECIMAL_DIG__ 17
#define __DEC_EVAL_METHOD__ 2
#define __ORDER_BIG_ENDIAN__ 4321
#define __UINT32_C(c) c ## UL
#define __INTMAX_MAX__ 9223372036854775807LL
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __FLT_DENORM_MIN__ 1.4012984643248171e-45F
#define __INT8_MAX__ 127
#define __UINT_FAST32_TYPE__ unsigned int
#define __CHAR32_TYPE__ long unsigned int
#define __FLT_MAX__ 3.4028234663852886e+38F
#define __INT32_TYPE__ long int
#define __SIZEOF_DOUBLE__ 8
#define __FLT_MIN_10_EXP__ (-37)
#define __INTMAX_TYPE__ long long int
#define __DEC128_MAX_EXP__ 6145
#define __ATOMIC_CONSUME 1
#define __GNUC_MINOR__ 9
#define __UINTMAX_MAX__ 18446744073709551615ULL
#define __DEC32_MANT_DIG__ 7
#define __BUILTIN_TRICORE_SATBU 1
#define __DBL_MAX_10_EXP__ 308
#define __LDBL_DENORM_MIN__ 4.9406564584124654e-324L
#define __INT16_C(c) c
#define __STDC__ 1
#define __BUILTIN_TRICORE_NOP 1
#define __PTRDIFF_TYPE__ long int
#define __ATOMIC_SEQ_CST 5
#define __UINT32_TYPE__ long unsigned int
#define __BUILTIN_TRICORE_SATHU 1
#define __UINTPTR_TYPE__ long unsigned int
#define __DEC64_SUBNORMAL_MIN__ 0.000000000000001E-383DD
#define __DEC128_MANT_DIG__ 34
#define __LDBL_MIN_10_EXP__ (-307)
#define __SIZEOF_LONG_LONG__ 8
#define __GCC_ATOMIC_LLONG_LOCK_FREE 1
#define __LDBL_DIG__ 15
#define __FLT_DECIMAL_DIG__ 9
#define __UINT_FAST16_MAX__ 4294967295U
#define __GCC_ATOMIC_SHORT_LOCK_FREE 1
#define __UINT_FAST8_TYPE__ unsigned int
#define __ATOMIC_ACQ_REL 4
#define __ATOMIC_RELEASE 3
"
  - description: Tricore C++ Compiler
    match-language: CPP
    match-sources: ".*\\.cpp"
    match-compiler-exe: "(.*/)?tricore-(elf-)?g++(\\.exe)?"
    include-dirs: ${compiler-exe-dir}/../tricore/include
    defines-text: "
#define __DBL_MIN_EXP__ (-1021)
#define __cpp_attributes 200809
#define __UINT_LEAST16_MAX__ 65535
#define __ATOMIC_ACQUIRE 2
#define __FLT_MIN__ 1.1754943508222875e-38F
#define __GCC_IEC_559_COMPLEX 0
#define __UINT_LEAST8_TYPE__ unsigned char
#define __INTMAX_C(c) c ## LL
#define __CHAR_BIT__ 8
#define __UINT8_MAX__ 255
#define __WINT_MAX__ 4294967295U
#define __cpp_static_assert 200410
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __SIZE_MAX__ 4294967295UL
#define __WCHAR_MAX__ 2147483647
#define __DBL_DENORM_MIN__ double(4.9406564584124654e-324L)
#define __GCC_ATOMIC_CHAR_LOCK_FREE 1
#define __GCC_IEC_559 0
#define __FLT_EVAL_METHOD__ 0
#define __cpp_binary_literals 201304
#define __GCC_ATOMIC_CHAR32_T_LOCK_FREE 1
#define __cpp_variadic_templates 200704
#define __UINT_FAST64_MAX__ 18446744073709551615ULL
#define __SIG_ATOMIC_TYPE__ int
#define __DBL_MIN_10_EXP__ (-307)
#define __FINITE_MATH_ONLY__ 0
#define __GNUC_PATCHLEVEL__ 4
#define __UINT_FAST8_MAX__ 4294967295U
#define __has_include(STR) __has_include__(STR)
#define __DEC64_MAX_EXP__ 385
#define __INT8_C(c) c
#define __UINT_LEAST64_MAX__ 18446744073709551615ULL
#define __SHRT_MAX__ 32767
#define __LDBL_MAX__ 1.7976931348623157e+308L
#define __UINT_LEAST8_MAX__ 255
#define __GCC_ATOMIC_BOOL_LOCK_FREE 1
#define __UINTMAX_TYPE__ long long unsigned int
#define __BUILTIN_TRICORE_INSERT 1
#define __DEC32_EPSILON__ 1E-6DF
#define __UINT32_MAX__ 4294967295UL
#define __GXX_EXPERIMENTAL_CXX0X__ 1
#define __TRICORE_HAVE_SHUFFLE__ 1
#define __LDBL_MAX_EXP__ 1024
#define __WINT_MIN__ 0U
#define __SCHAR_MAX__ 127
#define __WCHAR_MIN__ (-__WCHAR_MAX__ - 1)
#define __INT64_C(c) c ## LL
#define __DBL_DIG__ 15
#define __TRICORE_CORE__ 0x162
#define __GCC_ATOMIC_POINTER_LOCK_FREE 1
#define __TRICORE_HAVE_MOV64__ 1
#define __SIZEOF_INT__ 4
#define __SIZEOF_POINTER__ 4
#define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 1
#define __USER_LABEL_PREFIX__
#define __STDC_HOSTED__ 1
#define __LDBL_HAS_INFINITY__ 1
#define __TRICORE_HAVE_DIV__ 1
#define __FLT_EPSILON__ 1.1920928955078125e-7F
#define __GXX_WEAK__ 1
#define __BUILTIN_TRICORE_SATB 1
#define __LDBL_MIN__ 2.2250738585072014e-308L
#define __BUILTIN_TRICORE_SATH 1
#define __DEC32_MAX__ 9.999999E96DF
#define __INT32_MAX__ 2147483647L
#define __SIZEOF_LONG__ 4
#define __STDC_ISO_10646__ 200009L
#define __UINT16_C(c) c
#define __DECIMAL_DIG__ 17
#define __has_include_next(STR) __has_include_next__(STR)
#define __LDBL_HAS_QUIET_NAN__ 1
#define __GNUC__ 4
#define __GXX_RTTI 1
#define __FLT_HAS_DENORM__ 1
#define __SIZEOF_LONG_DOUBLE__ 8
#define __BIGGEST_ALIGNMENT__ 4
#define __DBL_MAX__ double(1.7976931348623157e+308L)
#define __cpp_raw_strings 200710
#define __INT_FAST32_MAX__ 2147483647
#define __DBL_HAS_INFINITY__ 1
#define __INT64_MAX__ 9223372036854775807LL
#define __DEC32_MIN_EXP__ (-94)
#define __INT_FAST16_TYPE__ int
#define __STRICT_ANSI__ 1
#define __LDBL_HAS_DENORM__ 1
#define __cplusplus 201300L
#define __DEC128_MAX__ 9.999999999999999999999999999999999E6144DL
#define __INT_LEAST32_MAX__ 2147483647L
#define __USING_SJLJ_EXCEPTIONS__ 1
#define __DEC32_MIN__ 1E-95DF
#define __DEPRECATED 1
#define __cpp_rvalue_references 200610
#define __DBL_MAX_EXP__ 1024
#define __DEC128_EPSILON__ 1E-33DL
#define __PTRDIFF_MAX__ 2147483647L
#define __STDC_NO_THREADS__ 1
#define __GNUG__ 4
#define __LONG_LONG_MAX__ 9223372036854775807LL
#define __SIZEOF_SIZE_T__ 4
#define __cpp_rvalue_reference 200610
#define __SIZEOF_WINT_T__ 4
#define __STDC_NO_ATOMICS__ 1
#define __GXX_ABI_VERSION 1002
#define __BUILTIN_TRICORE_CMPSWAPW 1
#define __FLT_MIN_EXP__ (-125)
#define __BUILTIN_TRICORE_LROTATE 1
#define __tricore__ 1
#define __cpp_lambdas 200907
#define __INT_FAST64_TYPE__ long long int
#define __FP_FAST_FMAF 1
#define __DBL_MIN__ double(2.2250738585072014e-308L)
#define __FLT_MIN_10_EXP__ (-37)
#define __DEC128_MIN__ 1E-6143DL
#define __REGISTER_PREFIX__ %
#define __UINT16_MAX__ 65535
#define __DBL_HAS_DENORM__ 1
#define __UINT8_TYPE__ unsigned char
#define __NO_INLINE__ 1
#define __BUILTIN_TRICORE_SWAPMSKW 1
#define __FLT_MANT_DIG__ 24
#define __VERSION__ \"4.9.4 build on 2020-09-01\"
#define __UINT64_C(c) c ## ULL
#define __cpp_unicode_characters 200704
#define __HIGHTEC__ 1
#define __tricore 1
#define _STDC_PREDEF_H 1
#define __cpp_decltype_auto 201304
#define __TC162__ 1
#define __GCC_ATOMIC_INT_LOCK_FREE 1
#define __TRICORE_HAVE_LHA__ 1
#define __FLOAT_WORD_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __BUILTIN_TRICORE_RROTATE 1
#define __TRICORE_HAVE_FLOAT16__ 1
#define __INT32_C(c) c ## L
#define __DEC64_EPSILON__ 1E-15DD
#define __ORDER_PDP_ENDIAN__ 3412
#define __DEC128_MIN_EXP__ (-6142)
#define __INT_FAST32_TYPE__ int
#define __UINT_LEAST16_TYPE__ short unsigned int
#define __INT16_MAX__ 32767
#define __SIZE_TYPE__ long unsigned int
#define __UINT64_MAX__ 18446744073709551615ULL
#define __INT8_TYPE__ signed char
#define __cpp_digit_separators 201309
#define __ELF__ 1
#define __FLT_RADIX__ 2
#define __INT_LEAST16_TYPE__ short int
#define __LDBL_EPSILON__ 2.2204460492503131e-16L
#define __UINTMAX_C(c) c ## ULL
#define __SIG_ATOMIC_MAX__ 2147483647
#define __GCC_ATOMIC_WCHAR_T_LOCK_FREE 1
#define __SIZEOF_PTRDIFF_T__ 4
#define __BUILTIN_TRICORE_SWAPW 1
#define __DEC32_SUBNORMAL_MIN__ 0.000001E-95DF
#define __INT_FAST16_MAX__ 2147483647
#define __UINT_FAST32_MAX__ 4294967295U
#define __UINT_LEAST64_TYPE__ long long unsigned int
#define __FLT_HAS_QUIET_NAN__ 1
#define __FLT_MAX_10_EXP__ 38
#define __LONG_MAX__ 2147483647L
#define __TRICORE_HAVE_HPTOF__ 1
#define __DEC128_SUBNORMAL_MIN__ 0.000000000000000000000000000000001E-6143DL
#define __FLT_HAS_INFINITY__ 1
#define __BUILTIN_TRICORE_LDMST 1
#define __cpp_unicode_literals 200710
#define __UINT_FAST16_TYPE__ unsigned int
#define __cpp_attribute_deprecated 201309
#define __DEC64_MAX__ 9.999999999999999E384DD
#define __CHAR16_TYPE__ short unsigned int
#define __PRAGMA_REDEFINE_EXTNAME 1
#define __TRICORE_HAVE_FTOHP__ 1
#define __INT_LEAST16_MAX__ 32767
#define __DEC64_MANT_DIG__ 16
#define __UINT_LEAST32_MAX__ 4294967295UL
#define __GCC_ATOMIC_LONG_LOCK_FREE 1
#define __INT_LEAST64_TYPE__ long long int
#define __INT16_TYPE__ short int
#define __INT_LEAST8_TYPE__ signed char
#define __STDC_VERSION__ 199409L
#define __DEC32_MAX_EXP__ 97
#define __INT_FAST8_MAX__ 2147483647
#define __INTPTR_MAX__ 2147483647L
#define __EXCEPTIONS 1
#define __LDBL_MANT_DIG__ 53
#define __DBL_HAS_QUIET_NAN__ 1
#define __SIG_ATOMIC_MIN__ (-__SIG_ATOMIC_MAX__ - 1)
#define __cpp_return_type_deduction 201304
#define __INTPTR_TYPE__ long int
#define __UINT16_TYPE__ short unsigned int
#define __WCHAR_TYPE__ int
#define __SIZEOF_FLOAT__ 4
#define __UINTPTR_MAX__ 4294967295UL
#define __DEC64_MIN_EXP__ (-382)
#define __cpp_decltype 200707
#define __INT_FAST64_MAX__ 9223372036854775807LL
#define __GCC_ATOMIC_TEST_AND_SET_TRUEVAL 1
#define __FLT_DIG__ 6
#define __UINT_FAST64_TYPE__ long long unsigned int
#define __TRICORE_HAVE_CRCN__ 1
#define __INT_MAX__ 2147483647
#define __TRICORE_HAVE_FTOIZ__ 1
#define __INT64_TYPE__ long long int
#define __FLT_MAX_EXP__ 128
#define __DBL_MANT_DIG__ 53
#define __INT_LEAST64_MAX__ 9223372036854775807LL
#define __DEC64_MIN__ 1E-383DD
#define __WINT_TYPE__ unsigned int
#define __UINT_LEAST32_TYPE__ long unsigned int
#define __SIZEOF_SHORT__ 2
#define __LDBL_MIN_EXP__ (-1021)
#define __INT_LEAST8_MAX__ 127
#define __TRICORE_HAVE_POPCNT__ 1
#define __LDBL_MAX_10_EXP__ 308
#define __ATOMIC_RELAXED 0
#define __DBL_EPSILON__ double(2.2204460492503131e-16L)
#define __BUILTIN_TRICORE_IMASK 1
#define __UINT8_C(c) c
#define __INT_LEAST32_TYPE__ long int
#define __SIZEOF_WCHAR_T__ 4
#define __UINT64_TYPE__ long long unsigned int
#define __TRICORE__ 1
#define __INT_FAST8_TYPE__ int
#define __GNUC_STDC_INLINE__ 1
#define __DBL_DECIMAL_DIG__ 17
#define __DEC_EVAL_METHOD__ 2
#define __ORDER_BIG_ENDIAN__ 4321
#define __cpp_runtime_arrays 201304
#define __UINT32_C(c) c ## UL
#define __INTMAX_MAX__ 9223372036854775807LL
#define __cpp_alias_templates 200704
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __FLT_DENORM_MIN__ 1.4012984643248171e-45F
#define __INT8_MAX__ 127
#define __UINT_FAST32_TYPE__ unsigned int
#define __CHAR32_TYPE__ long unsigned int
#define __FLT_MAX__ 3.4028234663852886e+38F
#define __cpp_constexpr 200704
#define __INT32_TYPE__ long int
#define __SIZEOF_DOUBLE__ 8
#define __INTMAX_TYPE__ long long int
#define __DEC128_MAX_EXP__ 6145
#define __ATOMIC_CONSUME 1
#define __GNUC_MINOR__ 9
#define __UINTMAX_MAX__ 18446744073709551615ULL
#define __DEC32_MANT_DIG__ 7
#define __BUILTIN_TRICORE_SATBU 1
#define __DBL_MAX_10_EXP__ 308
#define __LDBL_DENORM_MIN__ 4.9406564584124654e-324L
#define __INT16_C(c) c
#define __cpp_generic_lambdas 201304
#define __STDC__ 1
#define __BUILTIN_TRICORE_NOP 1
#define __PTRDIFF_TYPE__ long int
#define __ATOMIC_SEQ_CST 5
#define __UINT32_TYPE__ long unsigned int
#define __BUILTIN_TRICORE_SATHU 1
#define __UINTPTR_TYPE__ long unsigned int
#define __DEC64_SUBNORMAL_MIN__ 0.000000000000001E-383DD
#define __DEC128_MANT_DIG__ 34
#define __LDBL_MIN_10_EXP__ (-307)
#define __SIZEOF_LONG_LONG__ 8
#define __cpp_user_defined_literals 200809
#define __GCC_ATOMIC_LLONG_LOCK_FREE 1
#define __LDBL_DIG__ 15
#define __FLT_DECIMAL_DIG__ 9
#define __UINT_FAST16_MAX__ 4294967295U
#define __GCC_ATOMIC_SHORT_LOCK_FREE 1
#define __UINT_FAST8_TYPE__ unsigned int
#define __cpp_init_captures 201304
#define __ATOMIC_ACQ_REL 4
#define __ATOMIC_RELEASE 3
"
